### ISSUE TITLE
some questions when I run your code

### ISSUE THREAD

**Issue by weikaiv** [XinyiZ001/CapsGNN#2]
Thanks for your help!
When I run your code:
Traceback (most recent call last):
  File "F:/CapsGNN-master-tensoeflow/main.py", line 186, in <module>
    main()
  File "F:/CapsGNN-master-tensoeflow/main.py", line 46, in main
    class_label_fname=class_labels_fname)
  File "F:\CapsGNN-master-tensoeflow\dataset_utils\GraphDataset.py", line 11, in __init__
    for file in os.listdir(input_dir):
FileNotFoundError: [WinError 3] System can not find the route.: 'data_plk/ENZYMES'

**Comment by XinyiZ001** [comment]
Hi,

According to your error report, I think it might be because that you didn't do data preparation.

Do you follow the steps listed in README file to generate ENZYME data?

Please feel free to contact at us if you still have more questions.

Best Regards,
Xinyi
________________________________
